---
abstract: 'extending Amon2::Web::Dispatcher::RouterSimple'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Web-Dispatcher-RouterSimple-Extended
no_index:
  directory:
    - inc
provides:
  Amon2::Web::Dispatcher::RouterSimple::Extended:
    file: lib/Amon2/Web/Dispatcher/RouterSimple/Extended.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
